apiVersion: apps/v1
kind: Deployment
#metadata print the name of the deployment and namespace
metadata:
  name: bloodbank-app
  namespace: bloodbank
  labels:
    app: bloodbank-app
#spec tell about the number of replicas, strategy, selector and template for the deployment
spec:
  replicas: 2

  revisionHistoryLimit: 10

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: bloodbank-app

  template:
    metadata:
      labels:
        app: bloodbank-app

    spec:
      containers:

      - name: bloodbank-app

        image: rohith35/blood-bankapp:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 80

        envFrom:
        - configMapRef:
            name: bloodbank-config
            
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"
