name: BloodBank CI/CD

on:
  push:
    branches:
      - master

env:
  DOCKER_REPOSITORY: ${{ vars.DOCKER_REPOSITORY }}
  APP_IMAGE: ${{ vars.APP_IMAGE }}
  NAMESPACE: ${{ vars.NAMESPACE }}
  DB_IMAGE: ${{ vars.DB_IMAGE }}

jobs:

  build:

    runs-on: self-hosted

    outputs:
      IMAGE_TAG: ${{ steps.tag.outputs.image_tag }}

    steps:

    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Generate Image Tag
      id: tag
      run: |
        TAG=$(date +'%Y%m%d').${{ github.run_number }}-${GITHUB_SHA::7}
        echo "image_tag=$TAG" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
        -u "${{ secrets.DOCKER_USERNAME }}" \
        --password-stdin

    - name: Build Docker Image
      run: |
        docker build \
          -t $DOCKER_REPOSITORY/$APP_IMAGE:${{ steps.tag.outputs.image_tag }} \
          -t $DOCKER_REPOSITORY/$APP_IMAGE:latest .

    - name: Push Docker Images
      run: |
        docker push $DOCKER_REPOSITORY/$APP_IMAGE:${{ steps.tag.outputs.image_tag }}
        docker push $DOCKER_REPOSITORY/$APP_IMAGE:latest
    - name: build Docker image for db 
      run: |
        docker build \
           -t $DOCKER_REPOSITORY/$DB_IMAGE:${{ steps.tag.outputs.image_tag }} \
           -t $DOCKER_REPOSITORY/$DB_IMAGE:v1 \
           ./database
    - name:
      run: |
        docker push $DOCKER_REPOSITORY/$DB_IMAGE:${{ steps.tag.outputs.image_tag }}
        docker push $DOCKER_REPOSITORY/$DB_IMAGE:v1

  deploy:

    needs: build

    runs-on: self-hosted

    env:
      IMAGE_TAG: ${{ needs.build.outputs.IMAGE_TAG }}

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.MASTER_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.MASTER_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy Application
      run: |
        ssh -o StrictHostKeyChecking=no \
        ${{ secrets.MASTER_USERNAME }}@${{ secrets.MASTER_HOST }} << EOF

        kubectl set image deployment/bloodbank-app \
        bloodbank-app=$DOCKER_REPOSITORY/$APP_IMAGE:$IMAGE_TAG \
        -n $NAMESPACE

        kubectl rollout status deployment/bloodbank-app \
        -n $NAMESPACE

        EOF

    - name: Verify Deployment
      run: |
        ssh -o StrictHostKeyChecking=no \
        ${{ secrets.MASTER_USERNAME }}@${{ secrets.MASTER_HOST }} << EOF

        kubectl get pods -n $NAMESPACE
        kubectl get svc -n $NAMESPACE
        kubectl get ingress -n $NAMESPACE

        EOF

    - name: Rollback
      if: failure()
      run: |
        ssh -o StrictHostKeyChecking=no \
        ${{ secrets.MASTER_USERNAME }}@${{ secrets.MASTER_HOST }} << EOF

        kubectl rollout undo deployment/bloodbank-app \
        -n $NAMESPACE

        EOF
