name: CI-CD

on:
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  APP_IMAGE: blood-bankapp
  DB_IMAGE: blood-bankdb
  NAMESPACE: bloodbank

jobs:
  build:

    runs-on: self-hosted

    outputs:
      IMAGE_TAG: ${{ steps.tag.outputs.image_tag }}

    steps:

    - uses: actions/checkout@v4

    - name: Generate Image Tag
      id: tag
      run: |
        DATE=$(date +'%Y%m%d')
        IMAGE_TAG=$DATE.${{ github.run_number }}

        echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Docker Login
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
        -u "${{ secrets.DOCKER_USERNAME }}" \
        --password-stdin

    - name: Build App
      run: |
        docker build \
        -t $DOCKER_USERNAME/$APP_IMAGE:${{ steps.tag.outputs.image_tag }} \
         -t $DOCKER_USERNAME/$APP_IMAGE:v1 \
        .

    - name: Push App
      run: |
        docker push \
        $DOCKER_USERNAME/$APP_IMAGE:${{ steps.tag.outputs.image_tag }}
        docker push $DOCKER_USERNAME/$APP_IMAGE:v1

    - name: Build DB
      run: |
        docker build \
        -t $DOCKER_USERNAME/$DB_IMAGE:${{ steps.tag.outputs.image_tag }} \
        -t $DOCKER_USERNAME/$DB_IMAGE:v1 \
        ./database

    - name: Push DB
      run: |
        docker push \
        $DOCKER_USERNAME/$DB_IMAGE:${{ steps.tag.outputs.image_tag }}
        docker push $DOCKER_USERNAME/$DB_IMAGE:v1
  deploy:

    needs: build

    runs-on: self-hosted

    env:
      IMAGE_TAG: ${{ needs.build.outputs.IMAGE_TAG }}

    steps:

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh

        echo "${{ secrets.MASTER_SSH_KEY }}" > ~/.ssh/id_rsa

        chmod 600 ~/.ssh/id_rsa

        ssh-keyscan -H ${{ secrets.MASTER_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy Application
      run: |
        ssh ${{ secrets.MASTER_USERNAME }}@${{ secrets.MASTER_HOST }} "

        kubectl set image deployment/bloodbank-app \
        bloodbank-app=$DOCKER_USERNAME/$APP_IMAGE:$IMAGE_TAG \
        -n $NAMESPACE

        kubectl rollout status deployment/bloodbank-app -n $NAMESPACE

        "

    - name: Deploy Database
      run: |
        ssh ${{ secrets.MASTER_USERNAME }}@${{ secrets.MASTER_HOST }} "

        kubectl set image statefulset/bloodbank-db \
        mysql=$DOCKER_USERNAME/$DB_IMAGE:$IMAGE_TAG \
        -n $NAMESPACE

        kubectl rollout status statefulset/bloodbank-db -n $NAMESPACE

        "

    - name: Verify
      run: |
        ssh ${{ secrets.MASTER_USERNAME }}@${{ secrets.MASTER_HOST }} "

        kubectl get pods -n $NAMESPACE
        kubectl get svc -n $NAMESPACE
        kubectl get ingress -n $NAMESPACE

        "

    - name: Rollback
      if: failure()
      run: |
        ssh ${{ secrets.MASTER_USERNAME }}@${{ secrets.MASTER_HOST }} "

        kubectl rollout undo deployment/bloodbank-app -n $NAMESPACE

        "
